# Generated by Django 3.1.7 on 2021-04-03 11:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='image', max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='img/%y')),
                ('plant_name', models.CharField(default='NULL', max_length=100)),
                ('plant_health', models.CharField(default='NULL', max_length=100)),
                ('longitude', models.DecimalField(decimal_places=16, default=Decimal('0'), max_digits=22)),
                ('latitude', models.DecimalField(decimal_places=16, default=Decimal('0'), max_digits=22)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
